apiVersion: v1
kind: Service
metadata:
  name: kubergo
  namespace: app
  labels:
    app: kubergo
spec:
  type: ClusterIP
  selector:
    app: kubergo
  ports:
    - name: http
      port: 80
      targetPort: http
