apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubergo
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: kubergo
  endpoints:
    - path: /metrics
      port: http
      interval: 15s
